<a href="https://colab.research.google.com/github/vrathod07/Tensorflow-and-Deep-Learning/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Tensors


In [ ]:
#importing tensors
import tensorflow as tf
print(tf.__version__)


2.4.1


In [ ]:
#create tensors as tf constants
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dimension
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the dimension
vector.ndim

1

In [ ]:
#create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#create a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

######Tensor  using variable

In [ ]:
scalar = tf.Variable(7)
scalar
scalar1 = tf.constant(10)
scalar1

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
scalar.assign(5)


<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=5>

##Creating random  tensor

In [ ]:
 #create random tensor 
W = tf.random.Generator.from_seed(42)
w = W.normal(shape = [10,7])
W1 = tf.random.Generator.from_seed(42)
w

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763,
        -1.8107855 ,  0.09988727],
       [-0.50998646, -0.7535805 , -0.57166284,  0.1480774 , -0.23362993,
        -0.3522796 ,  0.40621263],
       [-1.0523509 ,  1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ,
         0.99009085, -0.0876323 ],
       [-0.635568  , -0.6161736 , -1.9441465 , -0.48293006, -0.52447474,
        -1.0345329 ,  1.3066901 ],
       [-1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ,  0.45331386,
         1.1487608 , -1.2659091 ],
       [-0.47450137,  2.006022  ,  0.28288034, -0.30288252, -1.443651  ,
         1.0034493 ,  0.20857747],
       [ 0.35700995,  1.0648885 ,  1.2432485 , -2.2173238 ,  0.18706243,
         0.6617961 ,  0.01380118],
       [-0.24827152,  1.2111493 , -0.7199124 , -0.04082382,  2.6791053 ,
         1.0914806 ,  0.33149615],
       [-0.67958915,  0.44723678, -0.17811584,  0.24882518,  0.49689844,
         0.825

##Shuffle the order of the matrix

In [ ]:
not_shuffeled  = tf.constant([[10,7],
                              [3,4],
                              [2,5]])
not_shuffeled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
shuffeled_tensor = tf.random.shuffle(not_shuffeled,seed = 42)
shuffeled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.2390374], shape=(1,), dtype=float32)
tf.Tensor([0.22267115], shape=(1,), dtype=float32)


##Turn numpy arrays into tensors

In [ ]:
import numpy as np
numpy_A = np.arange(1,121,dtype = np.int32)
numpy_A.shape
numpy_A

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape = (2,3,4,5))
A

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]], dtype=int32)>

##Getting info from tensors

In [ ]:
#create a rank 4 (dimension) tensor
t = tf.zeros(shape = [2,3,4,5])
t

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
t[0][0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

# Get Various attributes

In [ ]:
print(t.dtype)
print(t.ndim)
print(t.shape)
print(t.shape[0])
print(t.shape[-1])
print(tf.size(t).numpy())

<dtype: 'float32'>
4
(2, 3, 4, 5)
2
5
120


##Indexing of tensors

In [ ]:
t[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
t[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
 #create a rank 2 tensor
 t2 = tf.constant([[1,2],
                   [3,4]])
 t2.ndim
 t2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
t2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
#Add in extra dimension
t3 = t2[...,tf.newaxis]
t3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
t2 = tf.expand_dims(t2,axis = 0)

In [ ]:
tf.expand_dims(t2,axis = -1)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=int32, numpy=
array([[[[1],
         [2]],

        [[3],
         [4]]]], dtype=int32)>

###Manipulating tensor

In [ ]:
T = tf.constant([[10,7],
                [3,4]])
T = T+10
T

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tf.math.multiply(T,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [ ]:
T

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
T = tf.matmul(T , T*10)
T

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6210, 5780],
       [4420, 4170]], dtype=int32)>

#Changing the datatype of a tensor

In [ ]:
B = tf.constant([1,2,3,4])
print(B.dtype)
C = tf.constant([1.5,2.6,3.7,4.8])
print(C.dtype)


<dtype: 'int32'>
<dtype: 'float32'>


In [ ]:
B = tf.cast(B, dtype = tf.float16)
B, B.dtype

(<tf.Tensor: shape=(4,), dtype=float16, numpy=array([1., 2., 3., 4.], dtype=float16)>,
 tf.float16)

#Aggregating Tensor

---



In [ ]:
# Get the absolute value
D = tf.constant([-3,-4])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [ ]:
 T = tf.constant(np.random.randint(0,100, size = 50))
 T

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([29, 32, 72, 33, 77, 52, 93, 70, 97, 32, 55, 76, 49, 30, 66, 98,  3,
       31, 68, 12,  8, 52, 47, 15, 13, 72, 51, 52, 87, 18, 45, 92, 67, 23,
       76, 94, 92, 68, 66, 81, 73, 97, 34, 37, 36, 96, 15, 46, 58, 11])>

In [ ]:
print(tf.reduce_mean(T))
print(tf.reduce_max(T))
print(tf.reduce_min(T))
print(tf.reduce_sum(T))
print(tf.math.reduce_std(tf.cast(T, dtype = tf.float32)))
print(tf.math.reduce_variance(tf.cast(T, dtype = tf.float32)))

tf.Tensor(53, shape=(), dtype=int64)
tf.Tensor(98, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(2697, shape=(), dtype=int64)
tf.Tensor(27.768623, shape=(), dtype=float32)
tf.Tensor(771.09644, shape=(), dtype=float32)


In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(T)


<tf.Tensor: shape=(), dtype=int64, numpy=771>

In [ ]:
print(tf.math.argmax(T))

tf.Tensor(15, shape=(), dtype=int64)


In [ ]:
#creating a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#find positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#Index our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

###Squeezing a tensor 

In [ ]:
##create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
s = tf.squeeze(G)
s, s.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

#One Hot encoding

In [ ]:
l = [0,1,2,3]
tf.one_hot(l,depth = 4, dtype = tf.int32)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)>

In [ ]:
J = tf.constant(np.array([3,4,5,6]))
J , type(J.numpy())

(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 4, 5, 6])>,
 numpy.ndarray)

In [ ]:
J.numpy(), type(J.numpy())

(array([3, 4, 5, 6]), numpy.ndarray)